### PR TITLE
Added webcam features

### PR DESCRIPTION
**Pull request by KonradIT**
Thanks to @gurgelx for his [webcam project](https://github.com/gurgelx/GoProBetaHelper). 

Added:

- gpWebcam call driver
- helper method getWebcamIP
- Calls startWebcam, stopWebcam, webcamFOV and getWebcamPreview (launches VLC)
- renewWebcamIP (renews IP address)

### CODE REVIEW

**Comment by rmoriz** [comment]
Issues on MacOS 10.15.6 with Hero 8:

1. `GoProCamera.GoPro.getWebcamIP()` returns `10.5.5.9` but IP of GoPro is `172.28.128.51` (interface on macOS is assigned '172.28.128.54')

2. when manually adjusting the example to:
```
from goprocam import GoProCamera, constants
gopro = GoProCamera.GoPro(ip_address="172.28.128.51") # change
gopro.startWebcam(constants.Webcam.Resolution.R720p)
gopro.webcamFOV(constants.Webcam.FOV.Linear)
gopro.getWebcamPreview()
```

output:

```
python examples/launch_webcam_preview.py

HERO8 Black
HD8.01.02.00.00
Camera successfully connected!
VLC media player 3.0.11.1 Vetinari (revision 3.0.11.1-0-g52483f3ca2)                                    
```

but no stream is received.

GP8 display shows "webcam" but not with red background, so I assume the UDP trigger was not sent.

**Comment by rmoriz** [comment]
Update: GP8 works with manual IP and the following change:

```diff
diff --git i/goprocam/GoProCamera.py w/goprocam/GoProCamera.py
index fc22130..453ca0b 100644
--- i/goprocam/GoProCamera.py
+++ w/goprocam/GoProCamera.py
@@ -76,7 +77,7 @@ class GoPro:
         """Sends keep alive packet"""
         while True:
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
-            sock.sendto("_GPHD_:0:0:2:0.000000\n".encode(),
+            sock.sendto("_GPHD_:1:0:2:0.000000\n".encode(),
                         (self.ip_addr, 8554))
             time.sleep(2500/1000)
```

**Comment by KonradIT** [comment]
Hi, I want to debug the issue where your `getWebcamIP()` return 10.5.5.9, mind doing `ifconfig` and putting the correct interface as a parameter in `getWebcamIP()` (so `getWebcamIP("enp0s20u2") in my case)`.

I'll also fix the UDP keep alive issue.

**Comment by KonradIT** [comment]
If you want, do a PR with the changes you made, and I'll review it and merge it.

**Comment by rmoriz** [comment]
@KonradIT on macos the usb ethernet appears just as regular ethernet interface:

```
en8: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6407<RXCSUM,TXCSUM,VLAN_MTU,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 32:ff:7b:cf:c7:3f 
	inet6 fe80::26:4de7:ed48:221c%en8 prefixlen 64 secured scopeid 0x16 
	inet 172.28.128.55 netmask 0xffffff00 broadcast 172.28.128.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
```

**Comment by KonradIT** [comment]
Merging as it's pretty stable in my tests. I've been using this branch as my main branch for a week now to offload videos and photos using [GoProDashboard](http://github.com/konradit/goprodashboard) and cannot go back to use an SD card reader or MTP connection. Webcam stream *does* have about 500ms-1000ms of lag in my testing.

**Pull request merged**
